use serde::{Deserialize, Serialize};
use std::time::Duration;

// ── Multi-turn conversation types ────────────────────────────────────────────

/// Role of a participant in a multi-turn conversation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    User,
    Assistant,
}

/// A typed content block inside a [`Message`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    /// Plain text generated by the model or provided by the user.
    Text { text: String },
    /// A tool invocation emitted by the model.
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
    },
    /// The caller's response to a previous [`ContentBlock::ToolUse`].
    ToolResult {
        tool_use_id: String,
        content: String,
    },
}

/// A single message in a multi-turn conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub role: Role,
    pub content: Vec<ContentBlock>,
}

impl Message {
    /// Create a user-turn message with a single text block.
    pub fn user(text: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: vec![ContentBlock::Text { text: text.into() }],
        }
    }

    /// Create an assistant-turn message from an arbitrary list of blocks.
    pub fn assistant(blocks: Vec<ContentBlock>) -> Self {
        Self {
            role: Role::Assistant,
            content: blocks,
        }
    }

    /// Create a user-turn message carrying tool results back to the model.
    pub fn tool_results(results: Vec<ContentBlock>) -> Self {
        Self {
            role: Role::User,
            content: results,
        }
    }
}

/// Definition of a tool that the model may invoke.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    /// Unique tool name as the model will reference it.
    pub name: String,
    /// Human-readable description of what the tool does.
    pub description: String,
    /// JSON Schema document describing the tool's `input` object.
    pub input_schema: serde_json::Value,
}

/// Multi-turn inference request sent to [`LlmProvider::infer`](crate::LlmProvider::infer).
#[derive(Debug, Clone)]
pub struct InferenceRequest {
    /// Ordered conversation history.
    pub messages: Vec<Message>,
    /// Tools available to the model during this turn.
    pub tools: Vec<ToolDefinition>,
    /// Optional system prompt.
    pub system: Option<String>,
    /// Maximum tokens to generate.
    pub max_tokens: u32,
    /// Sampling temperature (provider-specific range).
    pub temperature: Option<f32>,
}

impl Default for InferenceRequest {
    fn default() -> Self {
        Self {
            messages: vec![],
            tools: vec![],
            system: None,
            max_tokens: 4096,
            temperature: None,
        }
    }
}

/// Response from [`LlmProvider::infer`](crate::LlmProvider::infer).
#[derive(Debug, Clone)]
pub struct InferenceResponse {
    /// Content blocks returned by the model.
    pub content: Vec<ContentBlock>,
    /// Reason the model stopped generating (e.g. `"end_turn"`, `"tool_use"`).
    pub stop_reason: String,
    /// Token usage statistics, if the provider reported them.
    pub usage: Option<Usage>,
    /// Display name of the provider that produced this response.
    pub provider: String,
}

impl InferenceResponse {
    /// Collect all [`ContentBlock::Text`] blocks into a single string.
    pub fn text(&self) -> String {
        self.content
            .iter()
            .filter_map(|b| {
                if let ContentBlock::Text { text } = b {
                    Some(text.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join("")
    }

    /// Returns `true` if the response contains at least one [`ContentBlock::ToolUse`] block.
    pub fn has_tool_calls(&self) -> bool {
        self.content
            .iter()
            .any(|b| matches!(b, ContentBlock::ToolUse { .. }))
    }
}

/// A single completion request sent to an LLM provider.
///
/// Build one directly or use the [`ainvoke!`](crate::ainvoke) /
/// [`invoke!`](crate::invoke) macros which fill in defaults for you.
#[derive(Debug, Clone)]
pub struct CompletionRequest {
    /// The user-visible prompt text.
    pub prompt: String,

    /// Optional system prompt. Providers that support a separate system role
    /// (Anthropic, OpenAI) use it natively; others prepend it to the user turn.
    pub system: Option<String>,

    /// Maximum number of tokens to generate. Defaults to `1024`.
    pub max_tokens: u32,

    /// When set, the provider is asked to return a JSON object conforming to
    /// this schema rather than free-form text. The mechanism varies by provider:
    /// Anthropic uses tool-use, OpenAI uses `response_format`, and Gemini uses
    /// `responseSchema`.
    pub schema: Option<JsonSchema>,

    /// Per-request HTTP timeout. Overrides the [`ProviderConfig`](crate::ProviderConfig)
    /// `request_timeout` for this call only.
    pub timeout: Option<Duration>,

    /// Per-request retry limit. Overrides [`RetryConfig`](crate::RetryConfig)
    /// `max_retries` for this call only. Only transient errors are retried.
    pub max_retries: Option<u32>,
}

impl Default for CompletionRequest {
    fn default() -> Self {
        Self {
            prompt: String::new(),
            system: None,
            max_tokens: 1024,
            schema: None,
            timeout: None,
            max_retries: None,
        }
    }
}

/// The response returned by a successful completion call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// The generated text. When a [`JsonSchema`] was requested this contains
    /// the raw JSON string returned by the provider.
    pub text: String,

    /// Display name of the provider that produced this response, e.g.
    /// `"anthropic/claude-sonnet-4-6"` or `"openai/gpt-4.1"`.
    pub provider: String,

    /// Token counts reported by the provider, if available.
    pub usage: Option<Usage>,
}

/// Token-usage statistics accompanying a completion response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Usage {
    /// Number of tokens in the prompt / input.
    pub input_tokens: u32,

    /// Number of tokens in the generated completion / output.
    pub output_tokens: u32,
}

/// A JSON Schema definition used to request structured output from a provider.
///
/// The schema is passed as a raw [`serde_json::Value`] so callers can construct
/// it with `serde_json::json!()`. Some providers (Gemini) strip unsupported
/// JSON Schema keywords automatically before sending.
#[derive(Debug, Clone)]
pub struct JsonSchema {
    /// A short identifier for the schema, used as the tool or format name sent
    /// to the provider API (e.g. `"sentiment_result"`).
    pub name: String,

    /// The JSON Schema document describing the expected output shape.
    pub schema: serde_json::Value,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_user_constructor() {
        let m = Message::user("hello");
        assert_eq!(m.role, Role::User);
        assert_eq!(m.content.len(), 1);
        assert!(matches!(&m.content[0], ContentBlock::Text { text } if text == "hello"));
    }

    #[test]
    fn message_assistant_constructor() {
        let block = ContentBlock::Text {
            text: "world".to_string(),
        };
        let m = Message::assistant(vec![block]);
        assert_eq!(m.role, Role::Assistant);
        assert_eq!(m.content.len(), 1);
    }

    #[test]
    fn message_tool_results_constructor() {
        let block = ContentBlock::ToolResult {
            tool_use_id: "id1".to_string(),
            content: "result".to_string(),
        };
        let m = Message::tool_results(vec![block]);
        assert_eq!(m.role, Role::User);
        assert!(matches!(&m.content[0], ContentBlock::ToolResult { .. }));
    }

    #[test]
    fn inference_response_text_concatenates_text_blocks() {
        let resp = InferenceResponse {
            content: vec![
                ContentBlock::Text {
                    text: "foo".to_string(),
                },
                ContentBlock::ToolUse {
                    id: "1".to_string(),
                    name: "calc".to_string(),
                    input: serde_json::Value::Null,
                },
                ContentBlock::Text {
                    text: "bar".to_string(),
                },
            ],
            stop_reason: "end_turn".to_string(),
            usage: None,
            provider: "test".to_string(),
        };
        assert_eq!(resp.text(), "foobar");
    }

    #[test]
    fn inference_response_has_tool_calls_true() {
        let resp = InferenceResponse {
            content: vec![ContentBlock::ToolUse {
                id: "1".to_string(),
                name: "search".to_string(),
                input: serde_json::json!({}),
            }],
            stop_reason: "tool_use".to_string(),
            usage: None,
            provider: "test".to_string(),
        };
        assert!(resp.has_tool_calls());
    }

    #[test]
    fn inference_response_has_tool_calls_false() {
        let resp = InferenceResponse {
            content: vec![ContentBlock::Text {
                text: "hi".to_string(),
            }],
            stop_reason: "end_turn".to_string(),
            usage: None,
            provider: "test".to_string(),
        };
        assert!(!resp.has_tool_calls());
    }

    #[test]
    fn content_block_serde_round_trip_text() {
        let block = ContentBlock::Text {
            text: "hello".to_string(),
        };
        let json = serde_json::to_string(&block).unwrap();
        let back: ContentBlock = serde_json::from_str(&json).unwrap();
        assert!(matches!(back, ContentBlock::Text { text } if text == "hello"));
    }

    #[test]
    fn content_block_serde_round_trip_tool_use() {
        let block = ContentBlock::ToolUse {
            id: "abc".to_string(),
            name: "search".to_string(),
            input: serde_json::json!({ "q": "rust" }),
        };
        let json = serde_json::to_string(&block).unwrap();
        let back: ContentBlock = serde_json::from_str(&json).unwrap();
        assert!(matches!(back, ContentBlock::ToolUse { id, .. } if id == "abc"));
    }

    #[test]
    fn content_block_serde_round_trip_tool_result() {
        let block = ContentBlock::ToolResult {
            tool_use_id: "xyz".to_string(),
            content: "42".to_string(),
        };
        let json = serde_json::to_string(&block).unwrap();
        let back: ContentBlock = serde_json::from_str(&json).unwrap();
        assert!(
            matches!(back, ContentBlock::ToolResult { tool_use_id, .. } if tool_use_id == "xyz")
        );
    }

    #[test]
    fn role_serde_lowercase() {
        let json = serde_json::to_string(&Role::User).unwrap();
        assert_eq!(json, r#""user""#);
        let json = serde_json::to_string(&Role::Assistant).unwrap();
        assert_eq!(json, r#""assistant""#);
    }

    #[test]
    fn inference_request_default_values() {
        let req = InferenceRequest::default();
        assert!(req.messages.is_empty());
        assert!(req.tools.is_empty());
        assert!(req.system.is_none());
        assert_eq!(req.max_tokens, 4096);
        assert!(req.temperature.is_none());
    }
}
