use serde::{Deserialize, Serialize};
use std::time::Duration;

/// A single completion request sent to an LLM provider.
///
/// Build one directly or use the [`ainvoke!`](crate::ainvoke) /
/// [`invoke!`](crate::invoke) macros which fill in defaults for you.
#[derive(Debug, Clone)]
pub struct CompletionRequest {
    /// The user-visible prompt text.
    pub prompt: String,

    /// Optional system prompt. Providers that support a separate system role
    /// (Anthropic, OpenAI) use it natively; others prepend it to the user turn.
    pub system: Option<String>,

    /// Maximum number of tokens to generate. Defaults to `1024`.
    pub max_tokens: u32,

    /// When set, the provider is asked to return a JSON object conforming to
    /// this schema rather than free-form text. The mechanism varies by provider:
    /// Anthropic uses tool-use, OpenAI uses `response_format`, and Gemini uses
    /// `responseSchema`.
    pub schema: Option<JsonSchema>,

    /// Per-request HTTP timeout. Overrides the [`ProviderConfig`](crate::ProviderConfig)
    /// `request_timeout` for this call only.
    pub timeout: Option<Duration>,

    /// Per-request retry limit. Overrides [`RetryConfig`](crate::RetryConfig)
    /// `max_retries` for this call only. Only transient errors are retried.
    pub max_retries: Option<u32>,
}

impl Default for CompletionRequest {
    fn default() -> Self {
        Self {
            prompt: String::new(),
            system: None,
            max_tokens: 1024,
            schema: None,
            timeout: None,
            max_retries: None,
        }
    }
}

/// The response returned by a successful completion call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// The generated text. When a [`JsonSchema`] was requested this contains
    /// the raw JSON string returned by the provider.
    pub text: String,

    /// Display name of the provider that produced this response, e.g.
    /// `"anthropic/claude-sonnet-4-6"` or `"openai/gpt-4.1"`.
    pub provider: String,

    /// Token counts reported by the provider, if available.
    pub usage: Option<Usage>,
}

/// Token-usage statistics accompanying a completion response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Usage {
    /// Number of tokens in the prompt / input.
    pub input_tokens: u32,

    /// Number of tokens in the generated completion / output.
    pub output_tokens: u32,
}

/// A JSON Schema definition used to request structured output from a provider.
///
/// The schema is passed as a raw [`serde_json::Value`] so callers can construct
/// it with `serde_json::json!()`. Some providers (Gemini) strip unsupported
/// JSON Schema keywords automatically before sending.
#[derive(Debug, Clone)]
pub struct JsonSchema {
    /// A short identifier for the schema, used as the tool or format name sent
    /// to the provider API (e.g. `"sentiment_result"`).
    pub name: String,

    /// The JSON Schema document describing the expected output shape.
    pub schema: serde_json::Value,
}

// ── Multi-turn inference types ───────────────────────────────────────────────

/// The role of a message participant in a multi-turn conversation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A message from the human / user side.
    User,
    /// A message generated by the assistant / model.
    Assistant,
    /// A system-level instruction (not supported as a turn by all providers).
    System,
}

/// A single content block within a message.
///
/// A message may contain multiple blocks (e.g. a text explanation followed by
/// a tool-use invocation).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    /// Plain text content.
    Text { text: String },
    /// A tool invocation requested by the model.
    ToolUse {
        /// Unique identifier for this tool call (used to match with results).
        id: String,
        /// The tool name to invoke.
        name: String,
        /// Arbitrary JSON arguments for the tool.
        input: serde_json::Value,
    },
    /// The result of a tool invocation, sent back to the model.
    ToolResult {
        /// The `id` from the corresponding [`ContentBlock::ToolUse`].
        tool_use_id: String,
        /// The tool output content.
        content: String,
    },
}

/// A single turn in a multi-turn conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Who authored this message.
    pub role: Role,
    /// The content of this message (one or more blocks).
    pub content: Vec<ContentBlock>,
}

impl Message {
    /// Create a user message with a single text block.
    pub fn user(text: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: vec![ContentBlock::Text { text: text.into() }],
        }
    }

    /// Create an assistant message with the given content blocks.
    pub fn assistant(content: Vec<ContentBlock>) -> Self {
        Self {
            role: Role::Assistant,
            content,
        }
    }

    /// Create a user message carrying tool results.
    pub fn tool_results(blocks: Vec<ContentBlock>) -> Self {
        Self {
            role: Role::User,
            content: blocks,
        }
    }
}

/// Description of a tool exposed to the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    /// The tool name (must match `ContentBlock::ToolUse::name`).
    pub name: String,
    /// Human-readable description sent to the model.
    pub description: String,
    /// JSON Schema describing the tool's `input` parameter shape.
    pub input_schema: serde_json::Value,
}

/// A multi-turn inference request with optional tool definitions.
///
/// Used with [`crate::LlmProvider::infer`] — distinct from
/// [`CompletionRequest`] which is single-turn text-only.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InferenceRequest {
    /// The conversation history so far.
    pub messages: Vec<Message>,
    /// Tool definitions available to the model.
    #[serde(default)]
    pub tools: Vec<ToolDefinition>,
    /// Optional system prompt.
    #[serde(default)]
    pub system: Option<String>,
    /// Maximum tokens to generate. Defaults to `1024`.
    #[serde(default = "default_max_tokens")]
    pub max_tokens: u32,
    /// Optional sampling temperature.
    #[serde(default)]
    pub temperature: Option<f32>,
}

fn default_max_tokens() -> u32 {
    1024
}

/// The reason the model stopped generating.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The model finished its response naturally.
    EndTurn,
    /// The model invoked one or more tools.
    ToolUse,
    /// The model reached the `max_tokens` limit.
    MaxTokens,
    /// An unrecognised stop reason returned by the provider.
    #[serde(other)]
    Other,
}

/// The response from a multi-turn inference call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InferenceResponse {
    /// The content blocks in the assistant's response.
    pub content: Vec<ContentBlock>,
    /// The reason the model stopped generating.
    pub stop_reason: StopReason,
    /// Token usage, if reported by the provider.
    #[serde(default)]
    pub usage: Option<Usage>,
    /// Provider name that produced this response.
    pub provider: String,
}

impl InferenceResponse {
    /// Returns `true` if any content block is a `ToolUse`.
    pub fn has_tool_calls(&self) -> bool {
        self.content
            .iter()
            .any(|b| matches!(b, ContentBlock::ToolUse { .. }))
    }

    /// Extract all text from `Text` blocks, joined with newlines.
    pub fn text(&self) -> String {
        self.content
            .iter()
            .filter_map(|b| {
                if let ContentBlock::Text { text } = b {
                    Some(text.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    }
}

#[cfg(test)]
mod inference_tests {
    use super::*;

    #[test]
    fn content_block_text_roundtrip() {
        let block = ContentBlock::Text {
            text: "hello".to_owned(),
        };
        let json = serde_json::to_string(&block).expect("serialize");
        let back: ContentBlock = serde_json::from_str(&json).expect("deserialize");
        assert!(matches!(back, ContentBlock::Text { text } if text == "hello"));
    }

    #[test]
    fn content_block_tool_use_roundtrip() {
        let block = ContentBlock::ToolUse {
            id: "call-1".to_owned(),
            name: "bash".to_owned(),
            input: serde_json::json!({"cmd": "echo hi"}),
        };
        let json = serde_json::to_string(&block).expect("serialize");
        let back: ContentBlock = serde_json::from_str(&json).expect("deserialize");
        assert!(matches!(back, ContentBlock::ToolUse { name, .. } if name == "bash"));
    }

    #[test]
    fn content_block_tool_result_roundtrip() {
        let block = ContentBlock::ToolResult {
            tool_use_id: "call-1".to_owned(),
            content: "hi\n".to_owned(),
        };
        let json = serde_json::to_string(&block).expect("serialize");
        let back: ContentBlock = serde_json::from_str(&json).expect("deserialize");
        assert!(
            matches!(back, ContentBlock::ToolResult { content, .. } if content == "hi\n")
        );
    }

    #[test]
    fn message_user_roundtrip() {
        let m = Message::user("hello world");
        let json = serde_json::to_string(&m).expect("serialize");
        let back: Message = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.role, Role::User);
    }

    #[test]
    fn inference_request_roundtrip() {
        let req = InferenceRequest {
            messages: vec![Message::user("hi")],
            tools: vec![],
            system: Some("be helpful".to_owned()),
            max_tokens: 512,
            temperature: None,
        };
        let json = serde_json::to_string(&req).expect("serialize");
        let back: InferenceRequest = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.max_tokens, 512);
        assert_eq!(back.system.as_deref(), Some("be helpful"));
    }

    #[test]
    fn inference_response_has_tool_calls_true() {
        let resp = InferenceResponse {
            content: vec![ContentBlock::ToolUse {
                id: "1".into(),
                name: "bash".into(),
                input: serde_json::json!({}),
            }],
            stop_reason: StopReason::ToolUse,
            usage: None,
            provider: "test".into(),
        };
        assert!(resp.has_tool_calls());
    }

    #[test]
    fn inference_response_text_extraction() {
        let resp = InferenceResponse {
            content: vec![ContentBlock::Text {
                text: "hello world".into(),
            }],
            stop_reason: StopReason::EndTurn,
            usage: None,
            provider: "test".into(),
        };
        assert_eq!(resp.text(), "hello world");
    }

    #[test]
    fn stop_reason_roundtrip() {
        let r = StopReason::EndTurn;
        let json = serde_json::to_string(&r).expect("serialize");
        let back: StopReason = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, StopReason::EndTurn);
    }

    #[test]
    fn tool_definition_roundtrip() {
        let def = ToolDefinition {
            name: "bash".to_owned(),
            description: "Run a shell command".to_owned(),
            input_schema: serde_json::json!({"type": "object"}),
        };
        let json = serde_json::to_string(&def).expect("serialize");
        let back: ToolDefinition = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.name, "bash");
    }
}
