name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: deny
        run: ~/.local/bin/mise exec -- cargo deny check
      - name: audit
        run: ~/.local/bin/mise exec -- cargo audit
