//! Domain types for multi-turn LLM conversations with tool use.
//!
//! These types are owned by `minibox-agent` and represent the agent's domain
//! model for structured conversation, independent of any specific LLM provider
//! wire format. Adapters (e.g. `AnthropicProvider`) map between these types
//! and their provider-specific API representations.

use serde::{Deserialize, Serialize};

/// The role of a message participant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A message from the human / user side.
    User,
    /// A message generated by the assistant / model.
    Assistant,
}

/// A single content block within a message.
///
/// A message may contain multiple blocks (e.g. a text explanation followed by
/// a tool-use invocation).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    /// Plain text content.
    Text { text: String },
    /// A tool invocation requested by the model.
    ToolUse {
        /// Unique identifier for this tool call (used to match with results).
        id: String,
        /// The tool name to invoke.
        name: String,
        /// Arbitrary JSON arguments for the tool.
        input: serde_json::Value,
    },
    /// The result of a tool invocation, sent back to the model.
    ToolResult {
        /// The `id` from the corresponding [`ContentBlock::ToolUse`].
        tool_use_id: String,
        /// The tool output content.
        content: String,
    },
}

/// A single turn in the conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Who authored this message.
    pub role: Role,
    /// The content of this message (one or more blocks).
    pub content: Vec<ContentBlock>,
}

impl Message {
    /// Create a user message with a single text block.
    pub fn user(text: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: vec![ContentBlock::Text { text: text.into() }],
        }
    }

    /// Create an assistant message with the given content blocks.
    pub fn assistant(content: Vec<ContentBlock>) -> Self {
        Self {
            role: Role::Assistant,
            content,
        }
    }

    /// Create a user message carrying tool results.
    pub fn tool_results(blocks: Vec<ContentBlock>) -> Self {
        Self {
            role: Role::User,
            content: blocks,
        }
    }
}

/// Description of a tool exposed to the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    /// The tool name (must match `ContentBlock::ToolUse::name`).
    pub name: String,
    /// Human-readable description sent to the model.
    pub description: String,
    /// JSON Schema describing the tool's `input` parameter shape.
    pub input_schema: serde_json::Value,
}

/// A multi-turn inference request with tool definitions.
///
/// Used by [`crate::agent::InferenceLlmProvider`] — distinct from
/// `minibox_llm::CompletionRequest` which is single-turn text-only.
#[derive(Debug, Clone)]
pub struct InferenceRequest {
    /// The conversation history so far.
    pub messages: Vec<Message>,
    /// Tool definitions available to the model.
    pub tools: Vec<ToolDefinition>,
    /// Optional system prompt.
    pub system: Option<String>,
    /// Maximum tokens to generate.
    pub max_tokens: u32,
    /// Optional sampling temperature.
    pub temperature: Option<f32>,
}

/// The response from a multi-turn inference call.
#[derive(Debug, Clone)]
pub struct InferenceResponse {
    /// The content blocks in the assistant's response.
    pub content: Vec<ContentBlock>,
    /// The reason the model stopped generating (e.g. `"end_turn"`, `"tool_use"`).
    pub stop_reason: String,
    /// Token usage, if reported by the provider.
    pub usage: Option<InferenceUsage>,
    /// Provider name that produced this response.
    pub provider: String,
}

impl InferenceResponse {
    /// Returns `true` if any content block is a `ToolUse`.
    pub fn has_tool_calls(&self) -> bool {
        self.content
            .iter()
            .any(|b| matches!(b, ContentBlock::ToolUse { .. }))
    }

    /// Extract all text from `Text` blocks, joined with newlines.
    pub fn text(&self) -> String {
        self.content
            .iter()
            .filter_map(|b| {
                if let ContentBlock::Text { text } = b {
                    Some(text.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Token-usage statistics for an inference response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InferenceUsage {
    /// Number of input tokens.
    pub input_tokens: u32,
    /// Number of output tokens.
    pub output_tokens: u32,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_user_creates_user_role() {
        let m = Message::user("hello");
        assert_eq!(m.role, Role::User);
        assert!(matches!(&m.content[0], ContentBlock::Text { text } if text == "hello"));
    }

    #[test]
    fn message_assistant_creates_assistant_role() {
        let m = Message::assistant(vec![ContentBlock::Text { text: "hi".into() }]);
        assert_eq!(m.role, Role::Assistant);
    }

    #[test]
    fn inference_response_has_tool_calls_true_when_tool_use_present() {
        let resp = InferenceResponse {
            content: vec![ContentBlock::ToolUse {
                id: "1".into(),
                name: "bash".into(),
                input: serde_json::json!({}),
            }],
            stop_reason: "tool_use".into(),
            usage: None,
            provider: "test".into(),
        };
        assert!(resp.has_tool_calls());
    }

    #[test]
    fn inference_response_text_extracts_text_blocks() {
        let resp = InferenceResponse {
            content: vec![ContentBlock::Text {
                text: "hello world".into(),
            }],
            stop_reason: "end_turn".into(),
            usage: None,
            provider: "test".into(),
        };
        assert_eq!(resp.text(), "hello world");
    }

    #[test]
    fn inference_response_has_tool_calls_false_for_text_only() {
        let resp = InferenceResponse {
            content: vec![ContentBlock::Text {
                text: "done".into(),
            }],
            stop_reason: "end_turn".into(),
            usage: None,
            provider: "test".into(),
        };
        assert!(!resp.has_tool_calls());
    }
}
