[book]
title = "minibox"
authors = []
language = "en"
src = "src"

[build]
build-dir = "dist"

[output.html]
git-repository-url = "https://www.github.com/89jobrien/minibox"
default-theme = "rust"
preferred-dark-theme = "ayu"
